### ISSUE TITLE
Problema com os testes

### ISSUE THREAD

**Issue by pedrohss9** [eminetto/ZendSkeletonApplication#6]
Olá,

Estou seguindo seu e-book zf2napratica e logo quando adicionei as classes Comments aparece um erro no test do phpunit que não consigo descobrir como solucionar. (estou começando agora com php e zend, provavelmente é bem simples resolver), mas isso já me tomou um bom tempo). Agradeço desde já
![errophpunit](https://cloud.githubusercontent.com/assets/12516456/13639031/9f9c40c8-e5ed-11e5-9e74-923e3375c967.JPG)

**Comment by pedrohss9** [comment]
segue a função onde indica o erro

  /**
     \* @expectedException Zend\Db\Adapter\Exception\InvalidQueryException
     \* @expectedExceptionMessage Statement could not be executed
     */

```
public function testUpdateInvalido()
{
    $tableGateway = $this->getTable('Application\Model\Comment');
    $comment = $this->addComment();

    $saved = $tableGateway->save($comment);
    $id = $saved->id;

    $comment = $tableGateway->get($id);
    $comment->post_id = 10;
    $updated = $tableGateway->save($comment);
}
```

**Comment by eminetto** [comment]
Vc conferiu se a sua classe Comment está exatamente igual a classe Comment do livro? Esse erro é de validação do campo description. Confere isso?

**Comment by pedrohss9** [comment]
sim, a classe Comment está exatamente igual a classe do livro, Conferi novamente (e também copiei do github pra ter certeza). 

SIm, é erro de description.

Se quiser posso te enviar o projeto para verificar.

Obrigado

**Comment by pedrohss9** [comment]
Agora que vi que mandei a imagem errada, pegava somente metade do erro.

Segue outra mais completa em anexo
![errophpunit](https://cloud.githubusercontent.com/assets/12516456/13650991/032044d8-e624-11e5-9cf8-aa9aeb23d459.JPG)

**Comment by eminetto** [comment]
Aparentemente algo mudou nesta versão do Zend, ou algo mais maligno está ocorrendo aí na sua máquina, porque a validação da classe Entity está reclamando que a descrição que vc está mandando é inválida. Tenta colocar um texto menor no campo description na função $this->addComment() e testar? Imagino que os acentos ou o script esteja causando o problema. Também pode ser algum erro de encoding da sua máquina, mas vc removendo os acentos e o código javascript de dentro do texto já podemos ver se é isso mesmo ;)

**Comment by pedrohss9** [comment]
ok, vou fazer os testes aqui e já te retorno

**Comment by pedrohss9** [comment]
Era problema com o acento!! Reduzi o tamanho da description e não mudou nada. Quando retirei o acento ele funcionou, apenas deu uma falha em um teste pq a strings não estavam iguais, mas isso já era esperado, arrumei isso e funcionou!

Muito obrigado pela atenção!
